export const Mock = [
  {
    id: 0,
    nome: 'Paolo',
    cognome: 'Ponzoni',
    messaggi: [
      { messaggio: 'ciao me', mio: false },
      { messaggio: 'ciao me ma sono io il vero me', mio: true },
      { messaggio: 'no sono io il vero me', mio: false },
      { messaggio: 'no sono io', mio: true },
      { messaggio: 'ok convincimi', mio: false },
      { messaggio: 'dimmi cosa ti rende te stesso', mio: false },
      { messaggio: 'questa e\' un ottima domanda', mio: true },
      { messaggio: 'sicuramente e\' importante dire che la serieta\' e\' cio\' che piu mi contraddistingue', mio: true },
      { messaggio: 'mi piace giocare a calcio', mio: true },
      { messaggio: 'ma non lo seguo... e\' noioso stare in panchina a guardare', mio: true },
      { messaggio: 'mi piace il blu', mio: true },
      { messaggio: 'Ok. Questo pero\' non ti rende unico, non ti rende te stesso, percio\' presumo tu abbia altri dati da offrirmi', mio: false },

    ],
    active: true,
  },
  {
    id: 0,
    nome: 'Zio',
    cognome: 'Peppino',
    messaggi: [
      { messaggio: 'ciao fuck', mio: false },
      { messaggio: 'ciao a bello', mio: true },
      { messaggio: 'ciao fuck', mio: false },
      { messaggio: 'ciao a bello', mio: true },
      { messaggio: 'ciao fuck', mio: false },
      { messaggio: 'ciao a bello', mio: true },
      { messaggio: 'ciao fuck', mio: false },
      { messaggio: 'ciao a bello', mio: true },
    ],
    active: false,
  },
  {
    id: 0,
    nome: 'Zio',
    cognome: 'Mariano',
    messaggi: [{ messaggio: 'ciao fuck', mio: false }],
    active: false,
  },
  {
    id: 0,
    nome: 'Nonno',
    cognome: 'Gianni',
    messaggi: [{ messaggio: 'ciao Onnis', mio: false }],
    active: false,
  },
];
