export const Mock = [
  {
    id: 0,
    nome: 'Paolo',
    cognome: 'Ponzoni',
    messaggi: [
      { messaggio: 'ciao fuck', mio: false },
      { messaggio: 'ciao a bello', mio: true },
      { messaggio: 'ciao fuck', mio: false },
      { messaggio: 'ciao a bello', mio: true },
      { messaggio: 'ciao fuck', mio: false },
      { messaggio: 'ciao a bello', mio: true },
      { messaggio: 'ciao fuck', mio: false },
      { messaggio: 'ciao a bello', mio: true },
      { messaggio: 'ciao fuck', mio: false },
      { messaggio: 'ciao a bello', mio: true },
      { messaggio: 'ciao fuck', mio: false },
      { messaggio: 'ciao a bello', mio: true },
      { messaggio: 'ciao fuck', mio: false },
      { messaggio: 'ciao a bello', mio: true },
      { messaggio: 'ciao fuck', mio: false },
      { messaggio: 'ciao a bello', mio: true },
      { messaggio: 'ciao fuck', mio: false },
      { messaggio: 'ciao a bello', mio: true },
      { messaggio: 'ciao fuck', mio: false },
      { messaggio: 'ciao a bello', mio: true },
      { messaggio: 'ciao fuck', mio: false },
      { messaggio: 'ciao a bello', mio: true },
    ],
  },
  {
    id: 0,
    nome: 'Zio',
    cognome: 'Peppino',
    messaggi: [{ messaggio: 'ciao fuck', mio: false }],
  },
  {
    id: 0,
    nome: 'Paolo',
    cognome: 'Ponzoni',
    messaggi: [{ messaggio: 'ciao fuck', mio: false }],
  },
  {
    id: 0,
    nome: 'Paolo',
    cognome: 'Ponzoni',
    messaggi: [{ messaggio: 'ciao fuck', mio: false }],
  },
  {
    id: 0,
    nome: 'Paolo',
    cognome: 'Ponzoni',
    messaggi: [{ messaggio: 'ciao fuck', mio: false }],
  },
  {
    id: 0,
    nome: 'Paolo',
    cognome: 'Ponzoni',
    messaggi: [{ messaggio: 'ciao fuck', mio: false }],
  },
  {
    id: 0,
    nome: 'Paolo',
    cognome: 'Ponzoni',
    messaggi: [{ messaggio: 'ciao fuck', mio: false }],
  },
];
